LANGUAGES = ["en", "vi"]

STRINGS = {
    "en": {
        "app_title": "xwinwrap Wallpaper Manager",
        "lang_name": "English",
        "status": "STATUS",
        "running": "●  Running",
        "stopped": "●  Stopped",
        "start": "Start",
        "stop": "Stop",
        "restart": "Restart",
        "ram": "RAM (mpv)",
        "cpu": "CPU",
        "video": "VIDEO WALLPAPER",
        "file_video": "Video file",
        "display_mode": "Display mode",
        "fullscreen": "Full screen",
        "window": "Custom window",
        "geometry": "Geometry (WxH+X+Y)",
        "geometry_ph": "1920x1080+0+0",
        "playback": "PLAYBACK",
        "fps": "FPS limit",
        "brightness": "Brightness",
        "speed": "Speed",
        "scale": "Scale quality",
        "scale_auto": "Auto (native)",
        "scale_1080p": "1080p",
        "scale_720p": "720p (lighter)",
        "scale_540p": "540p (lightest)",
        "behavior": "SMART BEHAVIOR",
        "pause_fullscreen": "Pause on fullscreen",
        "pause_maximize": "Pause on maximize",
        "audio": "Enable audio",
        "loop": "Loop forever",
        "hwdec": "GPU decode (vaapi)",
        "autostart": "Auto-start with system",
        "extra": "ADVANCED",
        "sticky": "Sticky (all workspaces)",
        "argb": "ARGB (transparency)",
        "override": "Override redirect",
        "screen": "Screen / Output",
        "screen_ph": "e.g. --screen=0 or leave empty",
        "desktop_type": "Desktop type",
        "fdt_default": "Default",
        "fdt_normal": "Normal (-fdt=0)",
        "fdt_desktop": "Desktop (-fdt=1)",
        "cmd": "GENERATED COMMAND",
        "copy": "Copy command",
        "save_script": "Save .sh script",
        "kill_all": "Kill all",
        "copy_done": "Copied!",
        "save_title": "Save script",
        "cancel": "Cancel",
        "save": "Save",
        "saved": "Saved: {path}",
        "error": "Error: {msg}",
        "err_no_file": "No valid video file selected",
        "err_start": "Failed to start: {detail}",
        "switch_lang": "Tiếng Việt",
        "video_files": "Video files",
        "missing_deps": "Missing tools:",
        "install_deps": "Install: sudo apt install",
        "add_wallpaper": "Add wallpaper",
        "no_wallpapers": "No wallpapers yet. Click + to add one.",
        "file_not_found": "File not found:\n{path}",
        "library_btn": "Library",
        "settings_btn": "Settings",
        "search_placeholder": "Search wallpapers...",
        "add_new": "Add new",
        "apply_now": "Apply now",
        "remove_from_list": "Remove",
        "now_playing": "Playing",
        "pause": "Pause",
    },
    "vi": {
        "app_title": "Trình quản lý hình nền xwinwrap",
        "lang_name": "Tiếng Việt",
        "status": "TRẠNG THÁI",
        "running": "●  Đang chạy",
        "stopped": "●  Đang dừng",
        "start": "Bật",
        "stop": "Tắt",
        "restart": "Khởi động lại",
        "ram": "RAM (mpv)",
        "cpu": "CPU",
        "video": "VIDEO WALLPAPER",
        "file_video": "File video",
        "display_mode": "Chế độ hiển thị",
        "fullscreen": "Full screen",
        "window": "Cửa sổ tùy chỉnh",
        "geometry": "Geometry (WxH+X+Y)",
        "geometry_ph": "1920x1080+0+0",
        "playback": "TÙY CHỈNH PHÁT",
        "fps": "FPS giới hạn",
        "brightness": "Độ sáng",
        "speed": "Tốc độ phát",
        "scale": "Scale chất lượng",
        "scale_auto": "Tự động (native)",
        "scale_1080p": "1080p",
        "scale_720p": "720p (nhẹ hơn)",
        "scale_540p": "540p (rất nhẹ)",
        "behavior": "HÀNH VI THÔNG MINH",
        "pause_fullscreen": "Tạm dừng khi cửa sổ fullscreen",
        "pause_maximize": "Tạm dừng khi cửa sổ maximize",
        "audio": "Bật âm thanh video",
        "loop": "Lặp lại liên tục",
        "hwdec": "Dùng GPU decode (vaapi)",
        "autostart": "Tự khởi động cùng hệ thống",
        "extra": "TÙY CHỌN NÂNG CAO",
        "sticky": "Sticky (mọi workspace)",
        "argb": "ARGB (transparency)",
        "override": "Override redirect",
        "screen": "Screen / Output",
        "screen_ph": "VD: --screen=0 hoặc để trống",
        "desktop_type": "Desktop type",
        "fdt_default": "Mặc định",
        "fdt_normal": "Normal (-fdt=0)",
        "fdt_desktop": "Desktop (-fdt=1)",
        "cmd": "LỆNH ĐƯỢC TẠO",
        "copy": "Copy lệnh",
        "save_script": "Tạo script .sh",
        "kill_all": "Kill tất cả",
        "copy_done": "Đã copy lệnh!",
        "save_title": "Lưu script",
        "cancel": "Hủy",
        "save": "Lưu",
        "saved": "Đã lưu: {path}",
        "error": "Lỗi: {msg}",
        "err_no_file": "Chưa chọn file video hợp lệ",
        "err_start": "Lỗi: {detail}",
        "switch_lang": "English",
        "video_files": "Video files",
        "missing_deps": "Thiếu công cụ:",
        "install_deps": "Cài đặt: sudo apt install",
        "add_wallpaper": "Thêm wallpaper",
        "no_wallpapers": "Chưa có wallpaper nào. Bấm + để thêm.",
        "file_not_found": "Không tìm thấy file:\n{path}",
        "library_btn": "Thư viện",
        "settings_btn": "Cài đặt",
        "search_placeholder": "Tìm kiếm wallpaper...",
        "add_new": "Thêm mới",
        "apply_now": "Áp dụng ngay",
        "remove_from_list": "Xóa",
        "now_playing": "Đang phát",
        "pause": "Tạm dừng",
    },
}
 

def _(key: str, lang: str = "en") -> str:
    return STRINGS.get(lang, {}).get(key, STRINGS.get("en", {}).get(key, key))
